name: 'ast-grep GH Action'
author: HerringtonDarkholme
description: 'A GH Action to run ast-grep custom rules'
inputs:
  version:
    description: 'The version of ast-grep to use in the action'
    default: ''
  config:
    description: "The file path to ast-grep's project config relative to root dir"
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: 'blue'
