on: [push]

jobs:
  sg-test:
    runs-on: ubuntu-latest
    name: A job to test ast-grep
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: ast-grep lint step
        id: basic
        uses: ./ # Uses an action in the root directory
      # Use the output from the `basic` step
      - name: Get the output time
        run: echo "The time was ${{ steps.basic.outputs.exitCode }}"
      - name: ast-grep lint step
        id: advanced
        uses: ./ # Uses an action in the root directory
        with:
          config: sgconfig.yml
          paths: src
      # Use the output from the `advanced` step
      - name: Get the output time
        run: echo "The time was ${{ steps.advanced.outputs.exitCode }}"
